import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#5a403e",
        "primary-fixed-dim": "#ffb3ac",
        "on-primary-container": "#ffd2cd",
        "surface-tint": "#b52526",
        "on-background": "#211a15",
        "on-secondary-fixed": "#281900",
        "primary-fixed": "#ffdad6",
        "inverse-primary": "#ffb3ac",
        "tertiary-fixed-dim": "#ffb77a",
        "surface-container-high": "#f4e5dd",
        "on-error": "#ffffff",
        "tertiary": "#703c00",
        "secondary-container": "#fdb72f",
        "tertiary-fixed": "#ffdcc2",
        "on-primary-fixed": "#410003",
        "surface-variant": "#efe0d8",
        "on-tertiary-fixed": "#2e1500",
        "on-primary": "#ffffff",
        "surface-dim": "#e6d7cf",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#6d3a00",
        "secondary-fixed": "#ffdeac",
        "primary-container": "#b82828",
        "surface": "#fff8f5",
        "surface-bright": "#fff8f5",
        "error-container": "#ffdad6",
        "background": "#fff8f5",
        "surface-container": "#faebe3",
        "tertiary-container": "#925000",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#fdeee6",
        "inverse-surface": "#372f29",
        "outline-variant": "#e2bebb",
        "on-secondary-fixed-variant": "#604100",
        "secondary": "#7e5700",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#ffba38",
        "primary": "#950913",
        "surface-container-highest": "#efe0d8",
        "on-primary-fixed-variant": "#920511",
        "on-tertiary-container": "#ffd4b3",
        "surface-container-low": "#fff1ea",
        "outline": "#8e706d",
        "on-surface": "#211a15",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#6c4a00",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "margin": "2rem",
        "gutter-mobile": "0.75rem",
        "gutter": "1.25rem",
      },
      fontFamily: {
        "headline-sm": ["Epilogue", "sans-serif"],
        "label-lg": ["JetBrains Mono", "monospace"],
        "label-md": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Epilogue", "sans-serif"],
        "display-lg-mobile": ["Epilogue", "sans-serif"],
        "display-lg": ["Epilogue", "sans-serif"],
        "headline-lg-mobile": ["Epilogue", "sans-serif"],
        "body-md": ["Work Sans", "sans-serif"],
        "title-md": ["Work Sans", "sans-serif"],
        "body-lg": ["Work Sans", "sans-serif"],
        "headline-md": ["Epilogue", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-lg": ["13px", { lineHeight: "18px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-md": ["11px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "800" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "0", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
